env:
  global:
    - CC_TEST_REPORTER_ID=e45cb4cbea2601c1f2c94402aac0be86b2a79b993fe669c06f53dd0069f23cfd

language: ruby

cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
